### ISSUE TITLE
Will not work on aarch64

### ISSUE THREAD

**Issue by berkus** [mvirkkunen/rtt-target#11]
I've noticed it has the same problem as jlink_rtt crate: it uses usize and *const u8 in the structures, making it incompatible with 64 bit builds. 

Both segger jlink sdk and openocd seem to have u32 hardcoded for the field sizes, i've worked around this by using u32 for all fields and also statically asserting the structures have correct sizes when compiling. 

If you're interested I can submit a PR with appropriate changes.

**Comment by mvirkkunen** [comment]
You're right in that 64-bit support is something I didn't even look at yet. It shouldn't be too complicated. Is RTT something people would use on a 64-bit system?

Additionally the pointer fields are pointer sized because they're, well, pointers. Surely on a 64-bit system they must be 64 bits long for things to work? The size/offset fields could still be 32-bit of course. Segger's own libraries specify the field types as `unsigned` and from what I remember it can be different sizes depending on settings.

**Comment by berkus** [comment]
> Is RTT something people would use on a 64-bit system?

Yeah, I'm using my own patched version of jlink_rtt currently on an Raspberry Pi target. It's handy when debugging with probe-rs or openocd.

> Surely on a 64-bit system they must be 64 bits long for things to work?

I do hope so, however for example [the OpenOCD implementation](http://openocd.zylin.com/#/c/4055/11) has pointers [hardcoded to 32 bits](http://openocd.zylin.com/#/c/4055/11/src/rtt/rtt.h) size even on 64 bits arch.

```
/** Channel name address on the target. */
uint32_t name_addr;
/** Buffer address on the target. */
uint32_t buffer_addr;
/** Channel buffer size in bytes. */
```

This might be a problem with OpenOCD though, so let me investigate a bit more. Maybe these changes are not really necessary and it would save us some effort to patch OpenOCD instead :)

> Segger's own libraries specify the field types as unsigned and from what I remember it can be different sizes depending on settings.

I've reviewed SEGGER SDK again and you're right, this seems like a problem with OpenOCD implementation. All the more reasons to stick with probe-rs.

Thanks! I think I'll close this now and thank you for rtt-target - this looks really great. If I have any improvements once I start integrating it, I'll open a PR.

**Comment by mvirkkunen** [comment]
Should I open an issue on probe-rs-rtt to add support for 64-bit targets or do you want to do it yourself?

**Comment by berkus** [comment]
@mvirkkunen i will check out probe-rs on actual arm64 target during next couple weeks and raise any issues if they appear. Don't worry!

**Comment by mvirkkunen** [comment]
probe-rs-rtt is definitely hardcoded (I wrote it) to expect 32 bit fields so it's very unlikely it would work.

**Comment by berkus** [comment]
Heh, i see. Then i (or you) will need to patch it.
