### ISSUE TITLE
rtt_init_print!() macro pollutes scope

### ISSUE THREAD

**Issue by etiandre** [mvirkkunen/rtt-target#17]
`rtt_init_print!()` (defined [here](https://github.com/mvirkkunen/rtt-target/blob/c505ed19d0602eedeaeab3948a52b5017d7136d1/rtt-target/src/print.rs#L185)) pollutes the scope of the function it's inserted into by creating a binding named  `channels`.

If the user creates another binding with the same name, it shadows the macro's one, and breaks rtt_target.

The only error message displayed using `cargo-embed` is `Failed to initialize RTT UI: No RTT channels configured`.

edit: this may be more complicated than it appears, i'm using RTIC 0.5, the problem may be on their side.

**Comment by mvirkkunen** [comment]
Hmm, the macro shouldn't pollute the scope because of how hygiene works. If you put `let _ = channels;` right after the call, does that compile...?

If you're using RTIC you might be running to the `wfi` bug in STM32/probe-rs: https://github.com/probe-rs/probe-rs/issues/350#issuecomment-740550519

**Comment by etiandre** [comment]
Yeah, seems I jumped to conclusions ! It doesn't appear to be the bug you linked either unfortunately. I'm having trouble reproducing the issue, for now it happens at random for me. I'll report back if I find something.
