### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by ildar** [mvirkkunen/rtt-target#19]
running `cargo build` fails with:
> ...
> error: couldn't read examples-cortex-m/memory.x: No such file or directory (os error 2)
>  --> examples-cortex-m/build.rs:7:55

adding `examples-cortex-m/memory.x` file also doesn't help much.
I know it's trivial to fix but IMHO should be documented somewhere.

**Comment by mvirkkunen** [comment]
That was a weird oversight on my part. Fixed in f1d5b9c7fe911e2d8164f634d612d4e62f875653. Thanks for the heads-up!
